name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired AWS region

      # Step 3: Delete failed stack if it exists
      - name: Delete failed stack if it exists
        run: |
          aws cloudformation describe-stacks --stack-name my-rds-stack && \
          aws cloudformation delete-stack --stack-name my-rds-stack && \
          aws cloudformation wait stack-delete-complete --stack-name my-rds-stack || echo "No stack to delete"

      # Step 4: Deploy CloudFormation stack
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file templates/demo.yaml \
            --stack-name my-rds-stack \
            --parameter-overrides VPCId=${{ secrets.VPC_ID }} \
            --capabilities CAPABILITY_NAMED_IAM
